### ISSUE TITLE
Invalid prometheus syntax in `pgexporter_pg_wal_last_received`

### ISSUE THREAD

**Issue by cracksalad** [pgexporter/pgexporter#110]
**Describe the bug**

In the metrics output I receive the following line:

`pgexporter_pg_wal_last_received{server="replica",="10_8_1_2:5432"} 2334`

There seems to be a missing label name. Prometheus is not able to parse the whole metrics output and just ignores it silently (it says "expected label name, got "EQUAL"" on the Status > Targets page).

The string `"10_8_1_2:5432"` seems to be IP address and port of the primary database. The error occurs on the secondary/replica.

**To Reproduce**

I guess you need to have a database that is set up as a replica. It might be noted, that I am using TimescaleDB and configured replication following [this guide](https://docs.timescale.com/self-hosted/latest/replication-and-ha/configure-replication/).

**Version**

0.4.0

**PostgreSQL**

PostgreSQL 14 with TimescaleDB 2.12

**libev**

4.24

**OpenSSL**

1.1.1k

**OS**

AlmaLinux 8.8

**Configuration**

pgexporter.conf:

```ini
[pgexporter]
host = 10.8.1.4
metrics = 5002

log_type = file
log_level = info
log_path = /var/log/pgexporter.log

[dev]
host = 127.0.0.1
port = 5432
user = pgexporter

[replica]
host = 127.0.0.1
port = 5433
user = pgexporter
```

There are two different database servers running on the host and both are observed using pgexporter.

**Prometheus**

Invalid Prometheus metrics:

`pgexporter_pg_wal_last_received{server="replica",="10_8_1_2:5432"} 2334`

All the other metrics seem to be alright.

**Debug logs**

Can you provide any debug logs (`log_level = debug5`) of the issue ?

Is there something specific to look for? If I search for strings like "wal", "last" or "received" in the log, I just find trace level entries about `wal_level` and `wal_sync_method`. Nothing else and nothing suspicious at all.

**Comment by resyfer** [comment]
Yeah I think I've identified the issue. I'll be fixing it in a couple of hours.

Just to confirm, I need two more things:

1) Can you please send the output of `pgexporter_pg_wal_last_received` metric of your `dev` server please (please do specify if it's not present) ?

2) And please send the output of this SQL query for your `replica` DB (this is the actual query that gets sent by pgexporter under the hood):
```sql
SELECT
  CASE
    WHEN sender_host LIKE '/%' THEN sender_host
    ELSE sender_host || ':' || sender_port::text
  END AS sender,
  EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - last_msg_send_time)) * 1000)::bigint AS time_elapsed_ms
FROM pg_stat_wal_receiver;
```

Thanks in advance!

**Comment by cracksalad** [comment]
Sounds great!

1. The dev server metric for `pgexporter_pg_wal_last_received` is indeed **not present**.
2. First there seems to be a missing `(` in your SQL query. I assume it should be placed before `EXTRACT`. The output then is
```SQL
SELECT
  CASE
    WHEN sender_host LIKE '/%' THEN sender_host
    ELSE sender_host || ':' || sender_port::text
  END AS sender,
  (EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - last_msg_send_time)) * 1000)::bigint AS time_elapsed_ms
FROM pg_stat_wal_receiver;

     sender      | time_elapsed_ms
-----------------+-----------------
 10.8.100.2:5432 |             165
(1 row)
```

I hope this helps. If there are any further questions, please just tell me. I would be pleased to see this bug fixed.

**Comment by resyfer** [comment]
> 1. The dev server metric for `pgexporter_pg_wal_last_received` is indeed **not present**.

Yeah thanks for this info!

> 2. First there seems to be a missing `(` in your SQL query. I assume it should be placed before `EXTRACT`.

Yeah I was providing it through my phone, so probably missed that while formatting. Thanks for this as well. I'll be making the fix soon!

**Comment by cracksalad** [comment]
Thank you very much for your work! I really appreciate it. 
Are there any plans to release this fix as v0.4.1 or something?

**Comment by resyfer** [comment]
@jesperpedersen

**Comment by jesperpedersen** [comment]
@cracksalad Does `0.4.x` work for you ? We can do releases on a weekly basis with bug fixes...

**Comment by jesperpedersen** [comment]
@cracksalad Did the stable branch work for you ? Or do you need the RPMs ?

**Comment by cracksalad** [comment]
@jesperpedersen RPMs would be nice, if you do not mind.

**Comment by resyfer** [comment]
Thanks for pointing out this bug! Feel free to report any bugs you find as well!
