### ISSUE TITLE
Quotes in `query` label of `pgexporter_pg_stat_statements_*` not escaped

### ISSUE THREAD

**Issue by cracksalad** [pgexporter/pgexporter#119]
**Describe the bug**

In the metrics output I find:
```
pgexporter_pg_stat_statements_calls{server="my_database",query="INSERT INTO "measurement" ("sensor_uuid", "value", "timestamp", "tags") VALUES($1,$2,$3,$4)"} 35400
```
As you can see, there are double quotes in the value of the `query` label which are not escaped and therefore break the syntax.

As far as I can tell, the following metrics are affected:

- `pgexporter_pg_stat_statements_calls`
- `pgexporter_pg_stat_statements_rows`
- `pgexporter_pg_stat_statements_total_exec_time`
- `pgexporter_pg_stat_statements_plans`
- `pgexporter_pg_stat_statements_wal_bytes`
 
... basically every pg_stat_statements metric with query label.

**To Reproduce**

1. Enable pg_stat_statements extension in your database
2. Use double quotes to escape table and column names in your queries

**Version**

Tested with release 0.4.0 as well as branch 0.4.x

**PostgreSQL**

14

**libev**

4.33

**OpenSSL**

3.0.7

**OS**

AlmaLinux 9.2

**Configuration**

pgexporter.conf:

```ini
[pgexporter]
host = 10.8.1.4
metrics = 5002

log_type = file
log_level = info
log_path = /var/log/pgexporter.log

unix_socket_dir = /tmp/

[my_database]
host = 127.0.0.1
port = 5432
user = pgexporter
```

**Prometheus**

Can you provide the output of the invalid Prometheus metrics ?

See above. There are of course multiple examples. If you need more to reproduce or understand the bug, just ask.

**Comment by jesperpedersen** [comment]
@resyfer Can you take a look at this ?

**Comment by cracksalad** [comment]
Could we just replace `SELECT calls, query` by `SELECT calls, REGEXP_REPLACE(query, '"', '\"') AS query` in [contrib/yaml/postgresql-XX.yaml](https://github.com/pgexporter/pgexporter/blob/775cb52ee815882695f7ab728922e7a376ca16db/contrib/yaml/postgresql-14.yaml#L506)?

**Comment by jesperpedersen** [comment]
Did you try that locally ?

**Comment by cracksalad** [comment]
> Did you try that locally ?

I tried `SELECT REGEXP_REPLACE('this is "a" \"test\"', '"', '\"', 'g');` which leads to `this is \"a\" \\"test\\"`. I did not test the change in the yaml file before, but I did it now and the change has absolutly no effect (or I tested the wrong way somehow).

**Comment by resyfer** [comment]
> Could we just replace `SELECT calls, query` with `SELECT calls, REGEXP_REPLACE(query, '"', '\"') AS query`?

I feel this is a possible solution... @jesperpedersen should I proceed with changing the queries or format the output itself?

Formatting the output will probably faster than a regexp (idk about internal optimizations of the query) and will help those who don't know about this issue, but regexp would help the user gain control of this (which I don't feel is a significant feature **in this case**) and is much easier to implement.

**Comment by jesperpedersen** [comment]
We should format our queries - internal and samples.

Users can use `REGEXP_REPLACE` in their YAML files if needed

**Comment by resyfer** [comment]
> We should format our queries - internal and samples.

So I'll be making changes in the SQL? Since the user and internal queries go through the same process, I would assume all of the internal queries would need to be updated using `REGEXP_REPLACE`.

If not SQL changes, then any changes in the C code for replacing `"` with `\"` would be reflected for both users and internal stuff.

**Comment by cracksalad** [comment]
Any updates on this? 
I am not the one to decide, but I think formatting the output is the cleanest solution, since escaping quotes is important for every metric in general and not specific to some SQL query results. This would make it easier to add further queries without the need to think about escaping. 
One could probably modify the function `safe_prometheus_key` in *libpgexporter/prometheus.c* to do this. Something like this needs to be integrated:
```c
int i = 0;
int j = 0;
while (key[i] != '\0')
{
   if (key[i] == '"' && (i == 0 || key[i - 1] != '\\'))  // avoid double escaping
   {
      escaped[j] = '\\';  // insert escaping backslash before each double quotes
      j++;
   }
   escaped[j] = key[i];  // copy every character

   j++;
   i++;
}
```
Problem is that this changes the length of the `key` which requires some reallocation of memory and I am not sure how to integrate it in a proper way into the code base. (In the code snippet `escaped` would be the resulting `key`)
Note that the if-statement checks for already escaped quotes to avoid double escaping, which would lead to an escaped backslash and unescaped quotes.

**Comment by jesperpedersen** [comment]
@resyfer WDYT ?

**Comment by resyfer** [comment]
@jesperpedersen @cracksalad LGTM, pretty similar to what I intended to do if we decided to make escaping as default. I also second the need to escape by default.

A _small_ addition to this code would be to first count the number of times we need to escape. It's a very unlikely situation that we do need to escape anything at all, as most results of queries do not really have `"` in my experience. In that case, we can prevent the need to copy everything as memory allocation takes way more time than an array traversal (especially with the modern CPU caching).

Sorry for not being available for the past few weeks, a lot of stuff happening, will need a couple of days more before I can get back to this, though if @cracksalad wants to, they can contribute to this of course.

**Comment by jesperpedersen** [comment]
`strchr` is an O(n) scan as well...

**Comment by resyfer** [comment]
> `strchr` is an O(n) scan as well...

Yep, but modern CPU caching makes [this way quicker](https://en.wikipedia.org/wiki/Locality_of_reference), and malloc is [very slow](https://blogs.sw.siemens.com/embedded-software/2015/07/06/malloc-just-say-no/), so I feel it's better to just check if it even needs escaping, as not needing escaping is a more likely scenario.

```c
// O(n) counter for escaping (would be considerably fast due to caching)

/* Likely Situation */
if(escaping_counter == 0) {
  return data;
}

/* Unlikely Situation */
// Allocate same sized memory plus extra unknown bytes, total size may as well be 2 * sizeof(original_array) in worst case
// Copy each byte
// Free
return escaped_data;
```

Would be significantly quicker imo.

**Comment by jesperpedersen** [comment]
The functionality is more important than the complexity of the function - we can always optimize once things are working

**Comment by vsuchard** [comment]
Hello, I'm facing the same issue, I would prefer to manage internal/default metrics outside of C code ... as the oracledb_exporter does. 
Anyway, my experience with saving full sql query in a prometheus db is not very good, I had to use string functions to save a just a part from the query for example just first word,  which defines select/update/delete/insert/dbms ... to make metrics working in grafana ..
Regards, Vlastislav

**Comment by jesperpedersen** [comment]
@vsuchard Thanks for your feedback !

**Comment by cracksalad** [comment]
> if @cracksalad wants to, they can contribute to this of course.

I definitly want to, but I probably need some help starting with this: Does anybody see a proper solution modifying `static char* safe_prometheus_key(char* key)` without changing the parameter type to `char**` to be able to use `realloc`? Since most of the calls look like the following snippet, we can not just prepend a `&` to the parameter value. So the change would be a bit complex and I would have to understand much more of the codebase.
```c
pgexporter_vappend(data, 5,
    ",",
    temp->query_alt->columns[j].name,
    "=\"",
    safe_prometheus_key(pgexporter_get_column(j, current)),
    "\""
    );
```
An alternative would be to use an additional allocated piece of memory and handle it independently, but I think that is not as "proper" as we all want it to be.
As soon as this is out of the way, I can create a draft PR, which is probably a good next step to discuss some details or missing parts/errors.

**Comment by resyfer** [comment]
@vsuchard Thanks for your feedback.

Also on a side note, if you want to modify internal metrics, you can:
1) create your own YAML file,
2) paste the internal metrics from [here](https://github.com/pgexporter/pgexporter/tree/main/contrib/yaml)
3) modify then according to your need and change the `collector` of the metric.
4) provide a `-Y` flag to give the path of the YAML, and remove the collector using `-C` as mentioned in the original copied metric.

@jesperpedersen I'm sorta conflicted on whether to apply a patch to the C code or the internal YAML metrics (in SQL)... I like the idea of a standard way that applies to all, since it does break stuff, but I also feel some people _may_ have an issue with that as well.

**Comment by resyfer** [comment]
> I definitly want to, but I probably need some help starting with this: Does anybody see a proper solution modifying `static char* safe_prometheus_key(char* key)` without changing the parameter type to `char**` to be able to use `realloc`? Since most of the calls look like the following snippet, we can not just prepend a `&` to the parameter value. So the change would be a bit complex and I would have to understand much more of the codebase.

Hmmm, I don't think there will be memory complications.

`key` is already allocated on the heap (you can see [here](https://github.com/pgexporter/pgexporter/blob/main/src/libpgexporter/queries.c#L540) and [here](https://github.com/pgexporter/pgexporter/blob/main/src/libpgexporter/queries.c#L783)), and the [function](https://github.com/pgexporter/pgexporter/blob/main/src/libpgexporter/prometheus.c#L1913) returns `key` as well (after making necessary modifications to it), so you don't have to worry about updating parameters...just return the **new** `key` if `key` requires escaping (and free the old one as well in that case).

**Comment by jesperpedersen** [comment]
@cracksalad It is an internal function - so you can change the API if you want

@resyfer Our built-in stuff needs to be safe, and we need to make sure that external YAML is safe as well

No matter what - it is something that needs to be fixed, so it will be a patch release - we just need to find the best solution, and the associated patch
