### ISSUE TITLE
Metric stat_bgwriter_information not working

### ISSUE THREAD

**Issue by vsuchard** [pgexporter/pgexporter#121]
**Describe the bug**

Query for the metric stat_bgwriter_information is not working because of missing of commas and it keeps errors in postgresql log.

**To Reproduce**

SELECT
                buffers_alloc
                buffers_backend
                buffers_backend_fsync,
                buffers_checkpoint
                buffers_clean
                checkpoint_sync_time,
                checkpoint_write_time
                checkpoints_req
                checkpoints_timed,
                maxwritten_clean
              FROM pg_stat_bgwriter;

**Version**
last

**PostgreSQL**
all n/a

**libev**
n/a

**OpenSSL**

n/a

**OS**

n/a

**Configuration**

n/a

* pgexporter.conf

**Prometheus**

* Dump

**Debug logs**

2024-01-17 13:22:12.614 CET ::1 pgexporter [3745604] [postgres]ERROR:  syntax error at or near "buffers_backend_fsync" at character 38
2024-01-17 13:22:12.614 CET ::1 pgexporter [3745604] [postgres]STATEMENT:  SELECT buffers_alloc buffers_backend buffers_backend_fsync, buffers_checkpoint buffers_clean checkpoint_sync_time, checkpoint_write_time checkpoints_req checkpoints_timed, maxwritten_clean FROM pg_stat_bgwriter;

**Tip**
Fix the query to add missing commas:

./src/include/internal.h

SELECT
                buffers_alloc,
                buffers_backend,
                buffers_backend_fsync,
                buffers_checkpoint,
                buffers_clean,
                checkpoint_sync_time,
                checkpoint_write_time,
                checkpoints_req,
                checkpoints_timed,
                maxwritten_clean
              FROM pg_stat_bgwriter;

**Comment by jesperpedersen** [comment]
Thanks for the report !

Patch has been merged

**Comment by jesperpedersen** [comment]
@vsuchard Try 0.4.1 - .rpm is coming...
