### ISSUE TITLE
Metric pg_stat_user_functions is not working

### ISSUE THREAD

**Issue by vsuchard** [pgexporter/pgexporter#122]
**Describe the bug**

Query for the metric pg_stat_user_functions not working , it is selecting column rows which does not exist for table pg_stat_user_functions, it keeps error in postgresql log.

**To Reproduce**
SELECT
                funcname,
                rows,
                self_time,
                total_time
              FROM pg_stat_user_functions;

**Version**
0.4.0 / 0.5.0

**PostgreSQL**

all 

**libev**

N/A

**OpenSSL**

N/A

**OS**

N/A

**Configuration**

N/A

* pgexporter.conf

**Prometheus**

no output 

* Dump

**Debug logs**

2024-01-17 17:59:42.654 CET ::1 pgexporter [3769688] [postgres]ERROR:  column "rows" does not exist at character 18
2024-01-17 17:59:42.654 CET ::1 pgexporter [3769688] [postgres]STATEMENT:  SELECT funcname, rows, self_time, total_time FROM pg_stat_user_functions;

**Tip**

replace rows with calls within the select 
postgres=# \d pg_stat_user_functions
            View "pg_catalog.pg_stat_user_functions"
   Column   |       Type       | Collation | Nullable | Default 
------------+------------------+-----------+----------+---------
 funcid     | oid              |           |          | 
 schemaname | name             |           |          | 
 funcname   | name             |           |          | 
 calls      | bigint           |           |          | 
 total_time | double precision |           |          | 
 self_time  | double precision |           |          | 

SELECT
                funcname,
                calls,
                self_time,
                total_time
              FROM pg_stat_user_functions;

Use \`\`\` before and after the text to keep the output as is.

**Comment by jesperpedersen** [comment]
Thanks for the report !

Patch has been merged
