### ISSUE TITLE
OS name is null in pgexporter_os_info() for Linux Mint

### ISSUE THREAD

**Issue by shikharish** [pgexporter/pgexporter#132]
The `name` parameter is empty in Linux Mint(and possibly other Ubuntu/Debian based distros)
```
postgres=# SELECT * FROM pgexporter_os_info();
 name |       version        | architecture |    host_name     | domain_name | process_count | uptime_seconds 
------+----------------------+--------------+------------------+-------------+---------------+----------------
      | Linux 6.5.0-1014-oem | x86_64       | shikhar-notebook | (none)      |           446 |          32791
(1 row)
```

**PostgreSQL**

What is the version of PostgreSQL ? 
`psql (PostgreSQL) 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)`

**OS**

Which Operating System (OS) is used ?
`Linux Mint virginia 21.3 x86_64`

---

This is happening because the OS name is extracted from the file `/etc/system-release` which is not present in many Linux distributions.

---

This might be the source to another bug: when the metrics is fetched from `pgexporter`, the curl command errors out.
```
❯ curl -v http://localhost:5002/metrics
*   Trying 127.0.0.1:5002...
* Connected to localhost (127.0.0.1) port 5002 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:5002
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.1; charset=utf-8
< Date: Thu Mar 28 23:56:51 2024
< Transfer-Encoding: chunked
< 
#HELP pgexporter_state The state of pgexporter
#TYPE pgexporter_state gauge
pgexporter_state 1

#HELP pgexporter_version The pgexporter version
#TYPE pgexporter_version counter
pgexporter_version{pgexporter_version="0.6.0"} 1

#HELP pgexporter_postgresql_active The state of PostgreSQL
#TYPE pgexporter_postgresql_active gauge
pgexporter_postgresql_active{server="primary"} 1

#HELP pgexporter_postgresql_version The PostgreSQL version
#TYPE pgexporter_postgresql_version gauge
pgexporter_postgresql_version{server="primary",version="PostgreSQL 14_11 (Ubuntu 14_11-0ubuntu0_22_04_1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11_4_0-1ubuntu1~22_04) 11_4_0, 64-bit"} 1

#HELP pgexporter_postgresql_uptime The PostgreSQL uptime in seconds
#TYPE pgexporter_postgresql_uptime counter
pgexporter_postgresql_uptime{server="primary"} 31542

#HELP pgexporter_postgresql_primary Is the PostgreSQL instance the primary
#TYPE pgexporter_postgresql_primary gauge
pgexporter_postgresql_primary{server="primary"} 1

#HELP pgexporter_version_ext pgexporter extension version
#TYPE pgexporter_version_ext gauge
pgexporter_version_ext{server="primary", pgexporter_version_ext="0.3.0"} 1

* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

This might be because [here](https://github.com/pgexporter/pgexporter/blob/56899d979c283239d9709c210bbd0ddd9eb6938c/src/libpgexporter/prometheus.c#L1012), `pgexporter_vappend()` is used to append strings and a null value is causing an error.

**Comment by jesperpedersen** [comment]
Is there something else we can use ?

**Comment by jesperpedersen** [comment]
Can you try to make a patch based on `pgexporter_exists(char* f)` ?

**Comment by resyfer** [comment]
I think the file `/etc/os-release` would be a better suited file for this. It looks like it is a part of [systemd](https://www.freedesktop.org/software/systemd/man/latest/os-release.html), which I think is available in most distros.

Also, as a fail safe, a "NULL" or "" (empty string) would be better in that place for cases where there isn't `systemd` (pgexporter seems to support that through [this patch](https://github.com/pgexporter/pgexporter/pull/68), though no formal testing has been carried out).

These three files can be checked (what `neofetch` does to get the OS name and kernel):

```sh
╭─resyfer@EOS ~ 
╰─$ cat /etc/lsb-release 
DISTRIB_ID="EndeavourOS"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME="rolling"
╭─resyfer@EOS ~ 
╰─$ cat /etc/os-release 
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"
╭─resyfer@EOS ~ 
╰─$ cat /proc/version 
Linux version 6.8.1-arch1-1 (linux@archlinux) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000
```

---

The vappend may be breaking due to this bug in pgexporter_ext as well, so it would be better to try again after fixing the above.

---

I can try to patch it if @shikharish is okay with it.

**Comment by shikharish** [comment]
@resyfer I would like to work on this.

**Comment by resyfer** [comment]
@shikharish Sure! Go ahead. Most of this involves [pgexporter_ext](https://github.com/pgexporter/pgexporter_ext) bits, but you probably knew that, since you mentioned the file 😄.

Btw, are any of these three files available in Mint?

**Comment by shikharish** [comment]
@resyfer Alright, I'll make a patch soon :)

Yes, all three of them are present.

**Comment by jesperpedersen** [comment]
Once we have this then we can do a patch release

**Comment by shikharish** [comment]
I realise that I should have opened this issue in pgmoneta_ext.
Have opened a PR.
