### ISSUE TITLE
Align CLI commands

### ISSUE THREAD

**Issue by jesperpedersen** [pgexporter/pgexporter#149]
Align the CLI commands with the sister projects - pgagroal and pgmoneta

**Comment by resyfer** [comment]
@jesperpedersen Can you clarify what exactly is needed here?

Not sure if I can commit to this as I'll be very busy till end of October, so I thought it's better to confirm.

**Comment by jesperpedersen** [comment]
It is about porting the improvements done in `cli.c` and `admin.c` in pgmoneta over to pgexporter

**Comment by jesperpedersen** [comment]
* `is-alive` -> `ping`
* `stop` -> `shutdown`
* `status` -> `status`
* `details` -> `status details`
* `reload` -> `conf reload`
* `reset` -> `clear prometheus`
