### ISSUE TITLE
Update CONTRIBUTING.md with installation instructions for Red Hat RPM based distributions

### ISSUE THREAD

**Issue by nikitabugrovsky** [pgexporter/pgexporter#21]
**Is your feature request related to a problem? Please describe.**

At the moment installation instructions reflect steps required to run builds on Fedora distribution. Steps for Red Hat RPM based distributions are slightly different. It is worth mentioning it.

**Describe the solution you'd like**

Extend CONTRIBUTING.md with steps relevant for Red Hat RPM based distributions.

**Comment by jesperpedersen** [comment]
First, the PostgreSQL ecosystem has discontinued support for CentOS 8 due to its unstable ABI.

Second, there are additional RPM based distributions, so I think it would be better to just write

```
For Red Hat RPM based distributions ...
```

**Comment by nikitabugrovsky** [comment]
@jesperpedersen thanks a lot for your comments. I made changes to the PR accordingly.
