### ISSUE TITLE
Custom Metrics

### ISSUE THREAD

**Issue by xRay2016** [pgexporter/pgexporter#40]
The pgexporter should support the customized metrics.

**Comment by jesperpedersen** [comment]
There are a couple of improvements that could be done as part of this issue.

1) `server` with `both`, `primary` and `replica` as values
2) `type` with `histogram`

We will leave them here for now...

**Comment by xRay2016** [comment]
I will submit the server type filter firstly.

**Comment by jesperpedersen** [comment]
The core functionality for custom queries is in.

Remaining work will be done as separate issues.

This concludes @xRay2016 's Google Summer of Code project ! Big thanks for all your effort !
