### ISSUE TITLE
An improvement to pgexporter_append for multiple 

### ISSUE THREAD

**Issue by resyfer** [pgexporter/pgexporter#56]
**Is your feature request related to a problem? Please describe.**

Realloc takes time, especially for cases where multiple calls to `pgexporter_append` are made consecutively.

**Describe the solution you'd like**

A improved version of `pgexporter_append` that can take in multiple inputs (usage like):

`pgexporter_vappend(orig, s1, s2, s3, ..., sn, APP_END);`

or,

`pgexporter_vappend(orig, n, s1, s2, s3, ..., sn);`

**What is the SQL statement you would like to support**

*N/A*

**Additional information**

It would then make `pgexporter_append` be a wrapper over `pgexporter_vappend`, and thus the other utilities like `pgexporter_append_int` etc. remain unaffected, and there's only improvement in performance.

**Comment by resyfer** [comment]
I would like to work on this issue please!

**Comment by resyfer** [comment]
@jesperpedersen I prefer the `n` way out of the two, and I wish I could remove the `n`, but I need to know when to stop iterating the function arguments.

**Comment by 2010YOUY01** [comment]
Is it possible to use `__VA_ARGS__`?
