### ISSUE TITLE
Strncpy output truncate build warning for prometheus.c

### ISSUE THREAD

**Issue by resyfer** [pgexporter/pgexporter#58]
**Describe the bug**

```sh
[  4%] Building C object src/CMakeFiles/pgexporter.dir/libpgexporter/prometheus.c.o
/pgexporter/src/libpgexporter/prometheus.c: In function ‘parse_list.isra’:
/pgexporter/src/libpgexporter/prometheus.c:2404:7: warning: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
 2404 |       strncpy(strs[idx], p, len);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/pgexporter/src/libpgexporter/prometheus.c:2401:13: note: length computed here
 2401 |       len = strlen(p);
      |             ^~~~~~~~~
```

**To Reproduce**

Clone the repo. Then:

```sh
$ mkdir build
$ cd build
$ cmake ..
$ make
```

**Version**
pgexporter v0.3.2

**PostgreSQL**
postgresql v15.2

**Compiler**
```sh
gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**OS**

```sh
             .',;::::;,'.                resyfer@fedora 
         .';:cccccccccccc:;,.            -------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 37 (Workstation Edition) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: Inspiron 3501 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.2.7-200.fc37.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 31 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2421 (rpm), 12 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.2.15 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 1920x1080 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 43.3 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Orchis-Dark [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Sevi-dark [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: gnome-terminal 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz 
:cccccccccccccccccccccccccccc:'.         GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
.:cccccccccccccccccccccc:;,..            Memory: 4660MiB / 7651MiB 
  '::cccccccccccccc::;,.

```

**Comment by resyfer** [comment]
I would like to work on issue please!

**Comment by jesperpedersen** [comment]
We should use pgexporter_append functions

**Comment by resyfer** [comment]
@jesperpedersen thank you for the suggestion. I'll use it instead of fixing the length then. I wanted to ask a few things as well:

1) Can you suggest something on this [line](https://github.com/pgexporter/pgexporter/blob/main/src/libpgexporter/prometheus.c#L2394) please? As far as I can understand, it aims to extract `c1,c2,c3,...,cn` from a string of `{c1,c2,c3,...,cn}`.

If that is the case, then the length of the extracted string would be `len - 2`, and giving an extra character for null, it would be `len - 1`, but provided length is `len`

This is throwing me off as I am worried if its my misunderstanding or just a minor overlook.

2) I was also wondering whether to switch `strtok` to `strtok_r` to make it thread-safe.

**Comment by jesperpedersen** [comment]
The "core" functions will use the `malloc` calls. And using `strtok` is ok - everything in pgexporter is a process

**Comment by jesperpedersen** [comment]
`strlen` doesn't count the `\0` character...

**Comment by resyfer** [comment]
> `strlen` doesn't count the `\0` character...

Yes sir, and this was my doubt:
![image](https://user-images.githubusercontent.com/74897008/228539662-a0e6f3d6-5c2f-4e15-8839-8b5e7d5fdabc.png)


so assuming I am understanding correctly, the malloc should be `malloc((len - 1) * sizeof(char))` instead of `malloc(len * sizeof(char))` and I wanted a confirmation if what I am understanding is correct.

**Comment by jesperpedersen** [comment]
But `len` is the length of the string, right ? So, you shouldn't cut off the last character

**Comment by resyfer** [comment]
> But `len` is the length of the string, right ? So, you shouldn't cut off the last character

This is what the code appears to do [here](https://github.com/pgexporter/pgexporter/blob/main/src/libpgexporter/prometheus.c#L2396) I think
